from tkinter import*
from tkinter import messagebox
new=Tk()
new.title("Hello")
new.geometry("1000x1000")
new.config(bg="green")
##def nextpage():
   ## messagebox.askyesno("Confirm","Are you sure")
    ##messagebox.showinfo("Done","Successfully ID Created")
    ##messagebox.showerror("Error","Not found")
def third():
    dd1=Frame(new,width=600,height=600,bg="red")
    dd1.place(x=0,y=0)
    a=Label(new,text="Third Page",font=("Century",18,"bold"),bg="black",fg="white")
    a.place(x=150,y=50)
    c=Button(new,text="Submit",font=("Ebrima",18,"italic"),bg="white",fg="Black" ,height=2 ,width=10,bd=10,command=nextpage)
    c.place(x=150,y=350)
def nextpage():    
    dd=Frame(new,width=1000,height=1000 ,bg="yellow")
    dd.place(x=0,y=0)
    a=Label(new,text="Welcome madam",font=("century",18,"bold"),bg="black",fg="white").place(x=150,y=50)
    c=Button(new,text="Submit",font=("Ebrima",18,"italic"),bg="white",fg="Black" ,height=2 ,width=10,bd=10,command=third)
    c.place(x=150,y=350)
a=Label(new,text="Personal Information",font=("Courier New Baltic",18,"italic"),bg="black",fg="white")
a.place(x=700,y=50)
d=Label(new,text="Name",font=("Courier New Baltic",18,"bold"),bg="black",fg="white")
d.place(x=550,y=150)
b=Entry(new,font=("Courier new Baltic",18,"italic"),bg="white",fg="black")
b.place(x=645,y=150)
#c=Button(new,text="Submit",font=("Ebrima",18,"italic"),bg="white",fg="Black" ,height=2 ,width=10,bd=10,command=new.destroy)
c=Button(new,text="Submit",font=("Ebrima",18,"italic"),bg="white",fg="Black" ,height=2 ,width=10,bd=10,command=nextpage)
c.place(x=800,y=800)
Radiobutton(new,text="op1").place(x=600,y=200)
Radiobutton(new,text="op2",value="op2").place(x=600,y=230)
Checkbutton(new,text="key").place(x=600,y=250)
Checkbutton(new,text="key value").place(x=600,y=270)
new.mainloop()
